"""empty message

Revision ID: 54f428465ccc
Revises: 
Create Date: 2025-07-02 22:31:19.064012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f428465ccc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offline_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=True),
    sa.Column('order_time', sa.Time(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('food_items', sa.JSON(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('online_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('order_time', sa.Time(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('food_items', sa.JSON(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tables_booked', sa.Integer(), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('reservation_date', sa.Date(), nullable=True),
    sa.Column('reservation_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_reservation')
    op.drop_table('online_order')
    op.drop_table('offline_order')
    # ### end Alembic commands ###
